vBot remove upstream version check (#82)
vBot upstream has been abandoned, last commit was in 2022, PR's are being ignored (for example https://github.com/Vithrax/vBot/pull/18 has been ignored since 2024)

and the check may cause sporadic network failures:

```
WARNING: [BOT] [vBot updater]: Unable to check version:
HttpSession timeout after 2 seconds
ERROR: TCP connection failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
ERROR: HttpSession unable to connect https://raw.githubusercontent.com/Vithrax/vBot/main/vBot/version.txt: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```